// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mbagssohubvrftvzdoso.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1iYWdzc29odWJ2cmZ0dnpkb3NvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4OTE0NzYsImV4cCI6MjA2OTQ2NzQ3Nn0.ucwZQKH6PIFECsWWkLsSpmUYtQuWoK5B_p7v4ZGd_iw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});